### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by hballinas** [adafruit/Bluefruit_LE_Connect#10]
Hello, 

I am including Adafruit's BLE breakout board into my projects now.  I completed the first one successfully and I'm moving into building the iOS and Android apps.  Well, IOS App first...

In any case, I am studying your code to base mine on the UART service.  When I try to run it on Xcode, the build fails.  Is this the latest version?

Thank you!

**Comment by microbuilder** [comment]
Please post support questions in the Adafruit support forum, thanks.

**Comment by jayjayesh** [comment]
Can you please provide us, steps how to implement Adafruit's BLE in my own project?
