### ISSUE TITLE
Navigation Bar occasionally disappears

### ISSUE THREAD

**Issue by dsn** [adafruit/Bluefruit_LE_Connect#12]
Randomly when connecting to a device the navigation bar fails to load which means you cannot disconnect from a device or return to the previous panel when you are for example in the color picker.

It appears to happen when you enter the controller panel as there is no navigation present there and you use the silver X to exit that screen. If you upload a new sketch while on the controller panel when the unit resets you are disconnected, this kicks you back to the device selection screen with a popup notification but the navigation bar does not return.

**Comment by dsn** [comment]
![img_0618](https://cloud.githubusercontent.com/assets/308030/8762617/2ccb1d80-2d33-11e5-90d7-6c68b698e4e2.PNG)

**Comment by CollinCunningham** [comment]
Thanks - this is fixed in v1.7.1!
