### ISSUE TITLE
Build errors in `BLEInterfaceController.swift`

### ISSUE THREAD

**Issue by narner** [adafruit/Bluefruit_LE_Connect#14]
I downloaded the latest version, and opened it on Xcode 6.3.1. When I opened it, I got some build errors on line 79 of `BLEInterfaceController.swift`. I attached a screen shot. Hope this is helpful! 

![screen shot 2015-08-02 at 10 26 06 am](https://cloud.githubusercontent.com/assets/2131591/9026560/0bc74616-3901-11e5-9264-aaa5ed82a132.png)

**Comment by CollinCunningham** [comment]
Should be all fixed after updating Xcode v6.4
