### ISSUE TITLE
"Adafruit_Bluefruit_LE_Connect-Swift.h" file not found

### ISSUE THREAD

**Issue by IAmOrion** [adafruit/Bluefruit_LE_Connect#17]
Can not build the app as the file "Adafruit_Bluefruit_LE_Connect-Swift.h" is missing and I don't seem to be able to locate it anywhere!

**Comment by CollinCunningham** [comment]
That file should be automatically generated by Xcode for Swift->ObjC interoperability.  What version of Xcode are using?

**Comment by IAmOrion** [comment]
Version 6.4 (6E35b)

**Comment by CollinCunningham** [comment]
hmm - I imagine there's a build setting for swift headers that's not enabled on your end.
