### ISSUE TITLE
"No Such module Moscapsule" in Xcode 7

### ISSUE THREAD

**Issue by Conner120** [adafruit/Bluefruit_LE_Connect#19]
When you try in Compile the the app in Xcode you You receive a error saying there's no such module Moscapsule. Appears to be the only error that currently is popping up. this error is in the MqttManager.swift on line 10

**Comment by antonio-openroad** [comment]
Make sure to always open the Xcode workspace instead of the project file when building the project.
Open Adafruit Bluefruit LE Connect.xcworkspace. It you open Adafruit Bluefruit LE Connect.xcodeproj the Pods project that contains the external libraries will be missing.
