### ISSUE TITLE
Xcode 7.0 errors

### ISSUE THREAD

**Issue by briggsm** [adafruit/Bluefruit_LE_Connect#20]
Hi, I recently upgraded to Xcode 7.0, and now am seeing various errors when trying to compile & run this code. Xcode asks if you'd like to update the Swift syntax. I tried that (got some errors), also tried NOT doing that, and got other errors. None seemed simple enough for me to figure out, even with some googling.  I'm pretty certain this can be easily reproduced by anybody running the latest Xcode 7.0, so I'm not including all the different errors messages, which are shown for each of the possible paths (updating to latest Swift syntax, not updating, etc).  If others are successful running this code as-is on Xcode 7.0, please let me know, then I can dig deeper & provide more details.

Note: I am opening the .xcworkspace file & not the .xcodeproj file.

Thanks!

**Comment by CollinCunningham** [comment]
currently working on updating the code for Swift 2.0

**Comment by CollinCunningham** [comment]
In the interim, the project should work fine with Xcode 6.4, which can be downloaded here:
https://developer.apple.com/downloads/
just use the search field on the left to find "Xcode 6.4"

**Comment by briggsm** [comment]
Thank you, good idea. I tried that, but I think I may be out of luck until you get a chance to update the code. Let me explain & see if I'm right....  I installed Xcode 6.4, it compiled, but when trying to upload the app to my device (iPhone 6 iOS 9), it didn't let me cuz the target is iOS 8.2, and with this older version of Xcode it doesn't have iOS 9 support. I tried also on my ancient iPhone 3GS, but that's maxed out at iOS 6.1 and apparently Swift only works with 7.0 and later. So I think I just need to wait, right?

I can use a Simulator, though when I run your app, it doesn't seem to find my Bluefruit module (or any other bluetooth devices). Guessing that's just a limitation of the simulator right?

Thanks for your thoughts.

**Comment by leemikes** [comment]
Here's how I got around that issue.

1) delete "derived data" from libraries 
2) rediscover devices using 6.4

Then should no longer appear in the incompat iOS list...

Sent from my iPhone

On Sep 29, 2015, at 1:17 AM, Mark Briggs <notifications@github.com> wrote:

Thank you, good idea. I tried that, but I think I may be out of luck until you get a chance to update the code. Let me explain & see if I'm right.... I installed Xcode 6.4, it compiled, but when trying to upload the app to my device (iPhone 6 iOS 9), it didn't let me cuz the target is iOS 8.2, and with this older version of Xcode it doesn't have iOS 9 support. I tried also on my ancient iPhone 3GS, but that's maxed out at iOS 6.1 and apparently Swift only works with 7.0 and later. So I think I just need to wait, right?

I can use a Simulator, though when I run your app, it doesn't seem to find my Bluefruit module (or any other bluetooth devices). Guessing that's just a limitation of the simulator right?

Thanks for your thoughts.

**Comment by briggsm** [comment]
Thanks for the idea. Tried it, but to no avail.  Doesn't list the device at all. I see it in Devices window, but with the warning that "Your iPhone may be running a version of iOS that is not supported by this version of Xcode"  (Xcode is 6.4, iPhone is running iOS 9)

**Comment by briggsm** [comment]
Found this just now. Not sure how I didn't see it earlier. It works to allow using iOS 9 with Xcode 6.4:
https://forums.developer.apple.com/thread/12993

**Comment by bashome** [comment]
Hi Guys,
Any update on when you think you'll have the code updated to Swift 2.0 and working in Xcode 7.1 for iOS9 ??  

Thanks
BAS

**Comment by ladyada** [comment]
still working on it - no ETA. will update this when its done. no need to remind us thx :)

**Comment by CollinCunningham** [comment]
main branch has been updated for Xcode 7.1, Swift 2, & WatchOS 2
