### ISSUE TITLE
moscapsule.swift

### ISSUE THREAD

**Issue by Conner120** [adafruit/Bluefruit_LE_Connect#21]
Two errors are received one of them is expressions are not allowed at the top level, and the other one is expecting member name or constructor call after type name Xcode version 7.1

<img width="1398" alt="screen shot 2015-09-20 at 5 00 54 pm" src="https://cloud.githubusercontent.com/assets/4810092/9983170/33a368d4-5fb9-11e5-9156-1b042e5c9ff2.png">

**Comment by CollinCunningham** [comment]
I'm not seeing this error - what version of xcode are you using?

**Comment by Conner120** [comment]
7.1

**Comment by linox11** [comment]
Hi,

I have the same problem ... any update ? I am using Xcode 7.1

Thanks

**Comment by CollinCunningham** [comment]
this should be fixed in the latest commit
