### ISSUE TITLE
An App ID with Identifier 'com.adafruit.bluefruitconnect.watchkitapp.watchkitextension'

### ISSUE THREAD

**Issue by linox11** [adafruit/Bluefruit_LE_Connect#23]
Hi,

I downloaded the document and opened the workplace. When running on the simulator it works fine, but when I want to run it on my iPad, I have this error 
An App ID with Identifier 'com.adafruit.bluefruitconnect.watchkitapp.watchkitextension' is not available. Please enter a different string

When I set up my profile, this another error pops out 
The 'iCloud' feature is only available to users enrolled in Apple Developer Program. Please visit 
https://developer.apple.com/programs/ to enroll.

Any solution ?
Note that I do not have a developer account as I do not need to pusblish on the App Syore
![screen shot 2015-11-13 at 21 25 11](https://cloud.githubusercontent.com/assets/15821051/11156588/1ab9d92a-8a4d-11e5-8e0e-f6e0b490e9e8.png)

**Comment by CollinCunningham** [comment]
unfortunately, free provisioning (running on a device w/o dev account) doesn't support capabilities such as icloud.  You'll need a developer account in order to run the app on a device unaltered.

**Comment by linox11** [comment]
Yes, but I dont wanna use any icloud, I just need the bluetooth capabilities. Is it possible ?

**Comment by vanessabullard** [comment]
I am also getting this error, but I've got a developer account and when I try to 'fix issue' it comes up with another error message saying 'An App ID with Identifier 'com.adafruit.bluefruitconnect' is not available. Please enter a different string.'

**Comment by linox11** [comment]
You can try changing the name "adafruit" with another one, like  "com.yourname.bluefruitconnect"
