### ISSUE TITLE
Signing issues / iCould

### ISSUE THREAD

**Issue by linox11** [adafruit/Bluefruit_LE_Connect#24]
Hi everybody,

I want to run the program on my iPad, but I have two issues : 
No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier “com.linox.bluefruitconnect” were found.

And when I click on fix it I have this : The 'iCloud' feature is only available to users enrolled in Apple Developer Program. Please visit https://developer.apple.com/programs/ to enroll. There was an error while interacting with the Developer Portal (9999, 4100).

At first I turned off the iCloud capabilities of the project, but now, i cannot check it anymore as it has disappeared from my target capabilities menu.

Any help please ?

Note : I don't have a developper account as I only need to use the app on my iPad without iCloud (I just need the BLE) the programs works on the simulators, but issues on the ipad.

**Comment by CollinCunningham** [comment]
Currently, a developer account is required to compile the project.
