### ISSUE TITLE
Is it possible to add background refresh?

### ISSUE THREAD

**Issue by mhellar** [adafruit/Bluefruit_LE_Connect#26]
I'm trying to get it to relay mqtt messages to the UART after I switch focus away from the app. I'm trying to add it myself but not much of an IOS Dev.

Thanks!

**Comment by antonio-openroad** [comment]
Hi, 
iOS restricts what an app can do while in background. It only allows some specific services as Bluetooth, VoIP or location to continue running. 
So its not possible at the moment to keep receiving Mqtt messages while the app is not in foreground.
