### ISSUE TITLE
iPad differs from iPhone

### ISSUE THREAD

**Issue by adamstener** [adafruit/Bluefruit_LE_Connect#30]
On the iPhone, if you filter out the devices based on signal strength, anything not matching the filter is removed from the list.  If you use the same parameters on the iPad, it seems like anything advertised with terrible signal strength still makes the list.  I would assume this has to do with an RSSI coming through that's a false positive value, and somehow this is managed on the phone differently than the iPad.

**Comment by antonio-openroad** [comment]
This repository is no longer maintained.
The new repository for the Bluefruit app is: https://github.com/adafruit/Bluefruit_LE_Connect_v2

This problem seems fixed on the new repository so I am closing the issue.
