### ISSUE TITLE
I get an error when try to run the project

### ISSUE THREAD

**Issue by renekaigen** [adafruit/Bluefruit_LE_Connect#32]
Bluefruit_LE_Connect-master/Pods/Moscapsule/Moscapsule/Moscapsule.swift:377:39: Cannot invoke initializer for type 'UnsafePointer<UInt8>' with an argument list of type '(UnsafeMutableRawPointer!)'

**Comment by microbuilder** [comment]
I'm afraid we don't/can't offer any support on the mobile apps. The source code is provided as a referencepurely 'as-is', but it isn't something we can actively support beyond our own in house needs to publish apps in the respective app stores. With limited resources, we need to focus our support team on embedded firmware and HW, and there are much larger mobile development communities out there for app development. Thanks for your understanding!
