### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by littlepedro78** [adafruit/Bluefruit_LE_Connect#7]
Hi there, nice work!!!! I would like to know if is possible to download old version without swift language.
Thanks

**Comment by Haifisch** [comment]
It would be nice to have two separate branches that splits the project between ObjC and Swift implementations, therefore we would have an example in both languages.

**Comment by heinemml** [comment]
The last version in ObjC is (I think) in this Commit: https://github.com/adafruit/Bluefruit_LE_Connect/tree/04f455543c61fd1d5ea01f0145fb1871c2fd6b1f
You can check it out via git or just download the .zip file as you would from current code.
